// Mock data for development — no API keys needed
export const MOCK_FILINGS = [
    {
        _id: "mock-1",
        accessionNumber: "0001234567-25-000123",
        cik: "0001234567",
        entityName: "Quantum Ventures Fund III, LP",
        entityType: "Limited Partnership",
        sicCode: "6726",
        industryGroupType: "Pooled Investment Fund",
        stateOfIncorporation: "DE",
        statesOfSolicitation: ["CA", "NY", "TX", "MA"],
        totalOfferingAmount: 75000000,
        totalAmountSold: 28500000,
        totalRemaining: 46500000,
        minimumInvestmentAccepted: 250000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: true,
        relatedPersons: [
            { firstName: "Sarah", lastName: "Chen", relationship: ["Executive Officer", "Director"] },
            { firstName: "Michael", lastName: "Torres", relationship: ["Executive Officer"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001234567",
    },
    {
        _id: "mock-2",
        accessionNumber: "0009876543-25-000456",
        cik: "0009876543",
        entityName: "NovaBio Therapeutics, Inc.",
        entityType: "Corporation",
        sicCode: "2836",
        industryGroupType: "Health Care",
        stateOfIncorporation: "MA",
        statesOfSolicitation: ["MA", "CA", "NY"],
        totalOfferingAmount: 15000000,
        totalAmountSold: 4200000,
        totalRemaining: 10800000,
        minimumInvestmentAccepted: 50000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: false,
        relatedPersons: [
            { firstName: "James", lastName: "Park", relationship: ["Executive Officer", "Director"] },
            { firstName: "Emily", lastName: "Richardson", relationship: ["Director"] },
            { firstName: "David", lastName: "Goldstein", relationship: ["Promoter"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0009876543",
    },
    {
        _id: "mock-3",
        accessionNumber: "0005551234-25-000789",
        cik: "0005551234",
        entityName: "Meridian Real Estate Partners, LLC",
        entityType: "Limited Liability Company",
        sicCode: "6512",
        industryGroupType: "Real Estate",
        stateOfIncorporation: "TX",
        statesOfSolicitation: ["TX", "FL", "AZ", "NV", "CO"],
        totalOfferingAmount: 42000000,
        totalAmountSold: 18900000,
        totalRemaining: 23100000,
        minimumInvestmentAccepted: 100000,
        isEquityType: true,
        isDebtType: true,
        isPooledInvestmentFund: false,
        relatedPersons: [
            { firstName: "Robert", lastName: "Williams", relationship: ["Executive Officer"] },
            { firstName: "Lisa", lastName: "Hernandez", relationship: ["Executive Officer", "Director"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0005551234",
    },
    {
        _id: "mock-4",
        accessionNumber: "0007778899-25-001234",
        cik: "0007778899",
        entityName: "Apex AI Systems Corp",
        entityType: "Corporation",
        sicCode: "7372",
        industryGroupType: "Technology",
        stateOfIncorporation: "CA",
        statesOfSolicitation: ["CA", "WA", "NY"],
        totalOfferingAmount: 8500000,
        totalAmountSold: 2100000,
        totalRemaining: 6400000,
        minimumInvestmentAccepted: 25000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: false,
        relatedPersons: [
            { firstName: "Anika", lastName: "Patel", relationship: ["Executive Officer", "Director"] },
            { firstName: "Chris", lastName: "Nakamura", relationship: ["Executive Officer"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0007778899",
    },
    {
        _id: "mock-5",
        accessionNumber: "0003334455-25-002345",
        cik: "0003334455",
        entityName: "GreenGrid Energy Storage Fund II",
        entityType: "Limited Partnership",
        sicCode: "4911",
        industryGroupType: "Energy",
        stateOfIncorporation: "NY",
        statesOfSolicitation: ["NY", "NJ", "CT", "PA"],
        totalOfferingAmount: 120000000,
        totalAmountSold: 67000000,
        totalRemaining: 53000000,
        minimumInvestmentAccepted: 500000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: true,
        relatedPersons: [
            { firstName: "Thomas", lastName: "Reynolds", relationship: ["Executive Officer"] },
            { firstName: "Maria", lastName: "Santos", relationship: ["Director"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0003334455",
    },
    {
        _id: "mock-6",
        accessionNumber: "0001112233-25-003456",
        cik: "0001112233",
        entityName: "Solaris Crypto Yield Fund",
        entityType: "Limited Partnership",
        sicCode: "6199",
        industryGroupType: "Banking & Financial Services",
        stateOfIncorporation: "WY",
        statesOfSolicitation: ["CA", "NY", "TX", "FL", "IL"],
        totalOfferingAmount: 250000000,
        totalAmountSold: 95000000,
        totalRemaining: 155000000,
        minimumInvestmentAccepted: 1000000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: true,
        relatedPersons: [
            { firstName: "Alex", lastName: "Volkov", relationship: ["Executive Officer", "Director"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001112233",
    },
    {
        _id: "mock-7",
        accessionNumber: "0006667788-25-004567",
        cik: "0006667788",
        entityName: "Pinnacle Growth Equity IV",
        entityType: "Limited Partnership",
        sicCode: "6726",
        industryGroupType: "Pooled Investment Fund",
        stateOfIncorporation: "DE",
        statesOfSolicitation: ["NY", "CA", "IL", "MA", "TX", "CT"],
        totalOfferingAmount: 500000000,
        totalAmountSold: 210000000,
        totalRemaining: 290000000,
        minimumInvestmentAccepted: 5000000,
        isEquityType: true,
        isDebtType: false,
        isPooledInvestmentFund: true,
        relatedPersons: [
            { firstName: "William", lastName: "Hartley", relationship: ["Executive Officer"] },
            { firstName: "Katherine", lastName: "Osei", relationship: ["Director"] },
            { firstName: "Jonathan", lastName: "Blake", relationship: ["Executive Officer"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
        formType: "D/A",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0006667788",
    },
    {
        _id: "mock-8",
        accessionNumber: "0004445566-25-005678",
        cik: "0004445566",
        entityName: "CedarPoint Infrastructure Debt Fund",
        entityType: "Limited Liability Company",
        sicCode: "6726",
        industryGroupType: "Pooled Investment Fund",
        stateOfIncorporation: "DE",
        statesOfSolicitation: ["NY", "CA", "TX"],
        totalOfferingAmount: 300000000,
        totalAmountSold: 145000000,
        totalRemaining: 155000000,
        minimumInvestmentAccepted: 2000000,
        isEquityType: false,
        isDebtType: true,
        isPooledInvestmentFund: true,
        relatedPersons: [
            { firstName: "Rachel", lastName: "Kim", relationship: ["Executive Officer", "Director"] },
        ],
        filedAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
        formType: "D",
        edgarUrl: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0004445566",
    },
];

export const MOCK_ALERT_RULES = [
    {
        _id: "rule-1",
        name: "Large VC Funds (>$50M)",
        enabled: true,
        filters: {
            sicCodes: ["6726"],
            states: [],
            minOfferingAmount: 50000000,
            maxOfferingAmount: null,
            watchlistCompanies: [],
            watchlistPersons: [],
        },
        triggerCount: 14,
        lastTriggered: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    },
    {
        _id: "rule-2",
        name: "Healthcare Startups in CA/MA",
        enabled: true,
        filters: {
            sicCodes: ["2836", "2835", "3841"],
            states: ["CA", "MA"],
            minOfferingAmount: null,
            maxOfferingAmount: null,
            watchlistCompanies: [],
            watchlistPersons: [],
        },
        triggerCount: 7,
        lastTriggered: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    },
    {
        _id: "rule-3",
        name: "Watch: David Goldstein",
        enabled: false,
        filters: {
            sicCodes: [],
            states: [],
            minOfferingAmount: null,
            maxOfferingAmount: null,
            watchlistCompanies: [],
            watchlistPersons: ["David Goldstein"],
        },
        triggerCount: 2,
        lastTriggered: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    },
];

export const MOCK_USER = {
    _id: "user-1",
    clerkUserId: "mock_clerk_id",
    email: "demo@filingpulse.com",
    name: "Demo User",
    subscriptionTier: "pro",
    subscriptionStatus: "active",
};

// SIC code lookup
export const SIC_CODES = {
    "2835": "Pharmaceutical Preparations",
    "2836": "Biological Products",
    "3572": "Computer Storage Devices",
    "3674": "Semiconductors",
    "3841": "Surgical & Medical Instruments",
    "4813": "Telephone Communications",
    "4911": "Electric Services",
    "5045": "Computers & Peripherals",
    "5961": "Catalog and Mail-Order Houses",
    "6021": "National Commercial Banks",
    "6022": "State Commercial Banks",
    "6159": "Federal-Sponsored Credit Agencies",
    "6199": "Finance Services",
    "6311": "Fire, Marine & Casualty Insurance",
    "6512": "Operators of Apartment Buildings",
    "6726": "Investment Offices",
    "7371": "Computer Services – Data Processing",
    "7372": "Prepackaged Software",
    "7374": "Computer Processing, Data Preparation",
};

export const US_STATES = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "DC",
];
